name: OpenTofu Plan on PR

on:
  pull_request:
    branches:
      - infra

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Run OpenTofu Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.READ_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
        with:
          tofu-version: latest

      - name: Run OpenTofu Plan for infrastructure
        working-directory: infra
        run: |
          tofu init
          tofu plan